# Generated by Django 3.2.13 on 2022-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0002_alter_mascota_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='observaciones',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
