# Generated by Django 3.2.13 on 2022-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('dueno', models.CharField(max_length=60)),
                ('observaciones', models.CharField(max_length=120)),
            ],
        ),
    ]
