# Generated by Django 3.2.13 on 2022-04-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0004_auto_20220424_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='X', max_length=2),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('G', 'Gato'), ('P', 'Perro'), ('C', 'Conejo'), ('H', 'Hamster')], default='X', max_length=3),
        ),
    ]
